name: Water Reminder Automation
on:
  schedule:
    - cron: '0 2,5,8,11,14,17 * * *'
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send FCM Notification
        uses: appleboy/fcm-action@master
        with:
          service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          token: "d7OyIRHiM55ud68XDsdTeM:APA91bHnfMMIwiOnGCFhZbHrecpNRGe2Cks03d6PiaiT3Eddyr46roKqXuuCRGD_8jXzb9eZvIjU59f4BPhqOxtZWNLjfmE4tu53Jx9g6zFwB_r2259xooE"
          title: "💧 Pani Peeyein!"
          body: "Haseeb Bhai, sehat ke liye ek glass pani peeyein."
          icon: "https://cdn-icons-png.flaticon.com/512/3105/3105807.png"
