name: Water Reminder Automation
on:
  schedule:
    - cron: '0 2,5,8,11,14,17 * * *'
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send FCM Notification
        # Yahan hum third-party tool bypass karke Google's direct method use karein ge
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
          pip install google-auth requests
          python - <<EOF
          import json, requests, google.auth.transport.requests, google.oauth2.service_account
          scoops = ['https://www.googleapis.com/auth/firebase.messaging']
          creds = google.oauth2.service_account.Credentials.from_service_account_file('service-account.json', scopes=scoops)
          creds.refresh(google.auth.transport.requests.Request())
          headers = {'Authorization': 'Bearer ' + creds.token, 'Content-Type': 'application/json'}
          payload = {
              "message": {
                  # Aapka naya Token yahan hai
                  "token": "c0Jmt3RD6c2HAoe_pOeek9:APA91bF910QQfOLxk-vyLG86l2gTGrN3aiMV2HmGXLFNwdkh0mLeUsmJ93gCPlYnbwOCHaln-lQtjexfMiTegP5dj8EudElQa3ZYSvNWniVvgAp-uJn0kRE",
                  "notification": {
                      "title": "💧 Pani Peeyein!",
                      "body": "Haseeb Bhai, sehat ke liye ek glass pani peeyein."
                  }
              }
          }
          response = requests.post("https://fcm.googleapis.com/v1/projects/water-aa9c4/messages:send", headers=headers, json=payload)
          print(response.status_code); print(response.text)
          EOF
